---
spring:
  profiles: dev
  jackson:
    serialization:
      write_dates_as_timestamps: false
  data:
    mongodb:
      uri: mongodb://localhost/establishments
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
test:
  stream: mytest2
