---
secret:
  word: JVM
---
spring:
  profiles: dev
  jackson:
    serialization:
      write_dates_as_timestamps: false
  data:
    mongodb:
      uri: mongodb://localhost/products
server:
  port: 8000
apis:
  establishments:
    url: http://localhost:8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
