---
secret:
  word: JVM
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost/products
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
